// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/admin/config.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_3758320803bf4c04, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Config is the settings for Commander.
type Config struct {
	Addr                 string     `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	ContextPath          string     `protobuf:"bytes,2,opt,name=contextPath,proto3" json:"contextPath,omitempty"`
	PublicPath           string     `protobuf:"bytes,3,opt,name=publicPath,proto3" json:"publicPath,omitempty"`
	Accounts             []*Account `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3758320803bf4c04, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Config) GetContextPath() string {
	if m != nil {
		return m.ContextPath
	}
	return ""
}

func (m *Config) GetPublicPath() string {
	if m != nil {
		return m.PublicPath
	}
	return ""
}

func (m *Config) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "v2ray.core.app.admin.Account")
	proto.RegisterType((*Config)(nil), "v2ray.core.app.admin.Config")
}

func init() { proto.RegisterFile("app/admin/config.proto", fileDescriptor_3758320803bf4c04) }

var fileDescriptor_3758320803bf4c04 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2c, 0x28, 0xd0,
	0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0xd3, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x29, 0x33, 0x2a, 0x4a, 0xac, 0xd4, 0x4b, 0xce, 0x2f, 0x4a, 0xd5, 0x4b,
	0x2c, 0x28, 0xd0, 0x03, 0x2b, 0x51, 0x72, 0xe4, 0x62, 0x77, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b,
	0x11, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d, 0xf2, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12,
	0x4c, 0x10, 0x39, 0x18, 0x5f, 0x69, 0x26, 0x23, 0x17, 0x9b, 0x33, 0xd8, 0x26, 0x21, 0x21, 0x2e,
	0x96, 0xc4, 0x94, 0x94, 0x22, 0xa8, 0x76, 0x30, 0x5b, 0x48, 0x81, 0x8b, 0x3b, 0x39, 0x3f, 0xaf,
	0x24, 0xb5, 0xa2, 0x24, 0x20, 0xb1, 0x24, 0x03, 0xaa, 0x1b, 0x59, 0x48, 0x48, 0x8e, 0x8b, 0xab,
	0xa0, 0x34, 0x29, 0x27, 0x33, 0x19, 0xac, 0x80, 0x19, 0xac, 0x00, 0x49, 0x44, 0xc8, 0x92, 0x8b,
	0x23, 0x11, 0xe2, 0xc6, 0x62, 0x09, 0x16, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x59, 0x3d, 0x6c, 0x9e,
	0xd1, 0x83, 0xfa, 0x24, 0x08, 0xae, 0xdc, 0xc9, 0x8a, 0x4b, 0x22, 0x39, 0x3f, 0x17, 0xab, 0xea,
	0x00, 0xc6, 0x28, 0x56, 0x30, 0x63, 0x15, 0x93, 0x48, 0x98, 0x51, 0x50, 0x62, 0xa5, 0x9e, 0x33,
	0x48, 0xde, 0xb1, 0xa0, 0x40, 0xcf, 0x11, 0x24, 0x9c, 0xc4, 0x06, 0x0e, 0x37, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0xa0, 0xae, 0x61, 0x51, 0x01, 0x00, 0x00,
}
