run:
  timeout: 5m

issues:
  new: true
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - stylecheck
      text: "ST1016:"
  exclude-files:
    - generated.*
    - .pb.go

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - errcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/v2fly/v2ray-core
  revive:
    rules:
      - name: blank-imports
        severity: warning
        disabled: true
  depguard:
    rules:
      Main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
